name: Realistic Auto Commits

on:
  schedule:
    - cron: "0 9 * * 1-5"   # every weekday at 09:00 UTC (2 PM Pakistan time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Git Identity
        run: |
          git config user.name "faqirullahafridi"
          git config user.email "196634821+faqirullahafridi@users.noreply.github.com"

      - name: Smart Commit Logic
        run: |
          DAY=$(date +%u)   # 1=Mon ... 5=Fri
          WEEK=$(date +%V)  # Week number

          # Pick a special day based on week number (changes weekly)
          SPECIAL_DAY=$(( (WEEK % 5) + 1 ))

          echo "Today is $DAY, Special day this week is $SPECIAL_DAY"

          # Always at least 1 commit
          echo "Commit on $(date)" >> activity_log.txt
          git add activity_log.txt
          git commit -m "auto: daily commit"
          git push

          # If today is the special day → make 3–5 extra commits
          if [ "$DAY" -eq "$SPECIAL_DAY" ]; then
            echo "Today is the special day → making extra commits"
            EXTRA=$(( (RANDOM % 3) + 3 ))  # random 3–5
            for i in $(seq 1 $EXTRA); do
              echo "Extra commit $i on $(date)" >> activity_log.txt
              git add activity_log.txt
              git commit -m "auto: extra commit $i for realism"
              git push
              sleep 10  # wait 10 seconds between commits
            done
          fi
