name: Keep Green

on:
  schedule:
    # Run at 10:00 UTC Mon–Fri
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config user.name "faqirullahafridi"
          git config user.email "196634821+faqirullahafridi@users.noreply.github.com"

      - name: Update Log
        run: |
          echo "Last run: $(date)" >> update.log

      - name: Random Multi Commit
        run: |
          RANDOM_DAY=$(( (RANDOM % 5) + 1 ))
          TODAY=$(date +%u)
          if [ "$TODAY" -eq "$RANDOM_DAY" ]; then
            echo "Doing multiple commits today..."
            for i in {1..3}; do
              echo "Extra commit $i on $(date)" >> update.log
              git add update.log
              git commit -m "Extra commit $i" || true
            done
          fi

      - name: Commit Changes
        run: |
          git add update.log
          git commit -m "Keep Green commit on $(date)" || echo "No changes to commit"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
